# Generated by Django 3.2.3 on 2021-09-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitball_app', '0002_auto_20210919_2014'),
    ]

    operations = [
        migrations.RenameModel('Devices', 'Device'),
    ]
