# Generated by Django 3.2.3 on 2021-09-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitball_app', '0003_auto_20210919_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
