# Generated by Django 3.2.3 on 2021-09-20 21:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitball_app', '0005_whoop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whoop',
            new_name='Connected_Device',
        ),
    ]
