# Generated by Django 3.2.3 on 2021-09-20 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitball_app', '0006_rename_whoop_connected_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connected_device',
            name='access_token',
        ),
        migrations.AddField(
            model_name='connected_device',
            name='device_access_token',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='connected_device',
            name='device_user_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='connected_device',
            name='device',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fitball_app.device'),
        ),
        migrations.AlterField(
            model_name='connected_device',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='connected_device',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
