# Generated by Django 3.2.3 on 2021-09-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitball_app', '0007_auto_20210920_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connected_device',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='connected_device',
            name='successful_login',
        ),
    ]
