# Generated by Django 3.2.3 on 2021-09-21 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitball_app', '0008_auto_20210921_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='connected_device',
            name='successful_login',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='connected_device',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitball_app.device'),
        ),
        migrations.AlterField(
            model_name='connected_device',
            name='device_access_token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='connected_device',
            name='device_user_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='connected_device',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='connected_device',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
