# Generated by Django 3.2.3 on 2021-09-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitball_app', '0010_auto_20210921_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='connected_device',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='connected_device',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
