# Generated by Django 3.2.3 on 2021-09-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitball_app', '0011_auto_20210921_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connected_device',
            name='successful_login',
        ),
    ]
