# Generated by Django 3.2.3 on 2021-09-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitball_app', '0017_goal_goal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
