# Generated by Django 3.2.3 on 2021-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitball_app', '0018_alter_goal_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal_metric',
            new_name='clean_goal_metric',
        ),
        migrations.AddField(
            model_name='goal',
            name='device_goal_metric',
            field=models.CharField(default='Sleep', max_length=200),
            preserve_default=False,
        ),
    ]
