# Generated by Django 3.2.3 on 2021-10-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitball_app', '0020_auto_20211011_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='frequency',
            field=models.CharField(default='Daily', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='metric_category',
            field=models.CharField(default='Daily', max_length=200),
            preserve_default=False,
        ),
    ]
