# Generated by Django 3.2.3 on 2021-10-13 00:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitball_app', '0021_auto_20211011_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='discord_channel_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
