# Generated by Django 3.2.3 on 2021-10-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitball_app', '0023_competition_clean_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord',
            name='discord_username',
            field=models.CharField(default='Matt', max_length=200),
            preserve_default=False,
        ),
    ]
